FROM rayproject/ray:2.39.0-py312-cpu
USER root
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ninja-build \
    cmake \
    libopenblas-dev \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*


RUN apt-get update -y \
    && apt-get install -y git wget vim numactl gcc-12 g++-12 python3 python3-pip libtcmalloc-minimal4 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

RUN apt-get install -y libopenblas-dev  ccache libomp-dev

USER ray
RUN python3 -m pip install --upgrade pip


RUN pip install intel-openmp
RUN pip install --pre --upgrade ipex-llm[cpp]

#ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:/usr/local/lib/libiomp5.so:$LD_PRELOAD"

#RUN pip install https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_dev/cpu/intel_extension_for_pytorch-2.3.100%2Bgit0eb3473-cp310-cp310-linux_x86_64.whl

RUN pip install --upgrade pip \
    && pip install wheel packaging ninja "setuptools>=49.4.0" numpy

# https://cmake.org/cmake/help/latest/module/FindBLAS.html#blas-lapack-vendors
RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings starlette-context
ENV CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-fopenmp -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS"
ENV FORCE_CMAKE=1
ENV GGML_BLAS_VENDOR=OpenBLAS
RUN CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-fopenmp"  LLAMA_OPENBLAS=1 python3 -m pip install llama-cpp-python==0.3.2 --verbose